# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 66fd52c
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: cedric.rossboth@epfl.ch
author_name: Cedric Rossboth
github_org: CedricRossboth
package_name: nmross
project_name: nmross
short_description: Gives an approximate 1H NMR when given a smiles or a IUPAC name
    of a molecule with maximum one aromatic ring and no double bonds.
